### ISSUE TITLE
header: dead link

### ISSUE THREAD

**Issue by eczajk1** [documentationjs/documentationjs.github.io#5]
The 'How to Write Docs' link in the header appears to be dead.  It is pointing here:

[https://github.com/documentationjs/documentation/blob/master/GETTTING_STARTED.md](https://github.com/documentationjs/documentation/blob/master/GETTTING_STARTED.md)

I'm not sure where it is supposed to point.

**Comment by tmcw** [comment]
:+1: thanks, fixed
